# -*- coding: utf-8 -*-
"""analise 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DVoaqiQQAXLIRBXRM6TSjwpXniyE_TaV
"""



"""# Base de dados ClientesBanco.csv

## 1. Importar base de dados (Planilha)

## 2. Importar a biblioteca Pandas.

## 3. Criar uma variável com o nome da tabela

## 4. fazer a limpeza e modelagem dos dados
"""

import pandas as pd

#lendo a base de dados (planilha) e armazenando em uma variável 
## enconding = 'latin'-1, serve como codificador para que os caracteres especiais sejam entendidos
### .head () é o metodo/função que utilizamos para mostrar os 5 primeiros registros
### display é o metodo/função que utilizamos para monstrar os 5 primeiros e os 5 ultimos itens da planilha - display(clientesBanco)

clientesBanco = pd.read_csv('ClientesBanco.csv',encoding = 'latin-1')
clientesBanco.head()

# fazendo a limpeza da base e eliminando os dados que não são essenciais
# A tabela sem a coluna de CLIENTNUM, vai ser armazenada em uma nova variável - clientesBancoLimpa

clientesBancoLimpa = clientesBanco.drop('CLIENTNUM', axis=1)
clientesBancoLimpa.head()

# para realizar a limpeza de uma linha especifica

clientesBancoLimpaLinha = clientesBancoLimpa.drop(0, axis = 0)
display(clientesBancoLimpaLinha)

# Somatorio de uma coluna numerica

somaLimiteConsumido = clientesBancoLimpa['Limite Consumido'].sum()
print(somaLimiteConsumido)

describeBanco = clientesBancoLimpa['Educação'].describe()
display(describeBanco)

somaLimiteEducacao = clientesBancoLimpa [['Educação','Limite Disponível']].groupby('Educação').sum()
display(somaLimiteEducacao)

medialimiteeducacao = clientesBancoLimpa[['Educação','Limite Disponível']].groupby('Educação').mean().round()
display(medialimiteeducacao)

# contador geral de todas as colunas da base de dados pela função DataFrame 

contadordecolunas = pd.DataFrame(clientesBancoLimpa)

# para achar os valores nulos

countEducacao = clientesBancoLimpa['Educação'].value_counts()
print(countEducacao)

# para a mesma soma acima, mas passando com um filtro (where ==)

registrosuperior = clientesBancoLimpa['Educação'] == 'Ensino Superior'
#registrosuperior.head()

somaregistrosuperior = registrosuperior.sum()
print(somaregistrosuperior)